# Generated by Django 5.1.1 on 2024-11-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasehistory',
            name='location',
        ),
        migrations.RemoveField(
            model_name='purchasehistory',
            name='quantity',
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='bottle_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='purchasehistory',
            name='purchase_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
