# Generated by Django 5.1.1 on 2024-11-04 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_remove_purchasehistory_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasehistory',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
